# Playback statistics
i script-binding stats/display-stats-toggle
I script-binding stats/display-page-4

Ctrl+h cycle-values hwdec "auto-safe" "vulkan" "vaapi" "no"

Ctrl+s cycle sub-visibility
Ctrl+S cycle secondary-sub-visibility
Ctrl+a cycle audio
Ctrl+- multiply speed 0.9091
Ctrl+= multiply speed 1.1
Ctrl+f cycle fullscreen
Ctrl+m cycle window-minimized
s async screenshot
S async screenshot video

F2 script-binding uosc/stream-quality
MBTN_RIGHT cycle pause
MENU script-binding uosc/menu
Ctrl+v script-binding uosc/paste-to-open
